### ISSUE TITLE
bug in Eric file

### ISSUE THREAD

**Issue by tinidev20** [tinidev20/GHtraining#3]
please fix your stuff!

**Comment by tinidev20** [comment]
Check out the file here [dev](/tinidev20/GHtraining/tree/dev)
Fix that stuff!

**Comment by tinidev20** [comment]
Here's a link to the file - maybe?
[Eric File](https://github.com/tinidev20/GHtraining/blob/dev/Eric)

**Comment by EricBarnhart** [comment]
Done Fixed It
